### ISSUE TITLE
[ios][14.1.2] Indicator not showing

### ISSUE THREAD

**Issue by heywhy** [nativescript-community/ui-pager#32]
The indicator is not showing up on iOS devices. After, going through the repository I found that the indicator is being referenced in the android context but missing in the iOS context.

References:

https://github.com/nativescript-community/ui-pager/blob/master/src/ui-pager/index.ios.ts
https://github.com/nativescript-community/ui-pager/blob/e667508495f78af9dd02c09e32357dae4044a1c4/src/ui-pager/index.android.ts#L127

**Comment by jcassidyav** [comment]
Should be fixed in 14.1.6
