### ISSUE TITLE
@nativescript-community/ui-pager version 13.0.21 not working in android

### ISSUE THREAD

**Issue by jitendraP-ashutec** [nativescript-community/ui-pager#7]
### Which platform(s) does your issue occur on?
- Android
- Android 9,10,11
- emulator 

Angular Version: 10.1.5
Nativescript/Angular version: 10.1.5
@nativescript/android verison: 8.0.0

### Please, provide the following version numbers that your issue occurs with:

When I install latest version of @nativescript-community/ui-pager: 13.0.21 its gives the below error.

```
ERROR Error: Uncaught (in promise): TypeError: record.factory is not a function
JS: TypeError: record.factory is not a function
JS:     at R3Injector.hydrate (file: node_modules/@angular/core/fesm2015/core.js:11289:0)
JS:     at R3Injector.get (file: node_modules/@angular/core/fesm2015/core.js:11111:0)
JS:     at file: node_modules/@angular/core/fesm2015/core.js:11148:0
JS:     at Set.forEach (<anonymous>)
JS:     at R3Injector._resolveInjectorDefTypes (file: node_modules/@angular/core/fesm2015/core.js:11148:0)
JS:     at new NgModuleRef$1 (file: node_modules/@angular/core/fesm2015/core.js:24236:0)
JS:     at NgModuleFactory$1.create (file: node_modules/@angular/core/fesm2015/core.js:24290:0)
JS:     at MapSubscriber.project (file: node_modules/@angular/router/fesm2015/router.js:3484:0)
JS:     at MapSubscriber.push.../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (file: node_modules/rxjs/_esm5/internal/operators/map.js:35:0). ```

**Comment by OzymandiasTheGreat** [comment]
I also just ran into this issue. Downgrading to 13.0.20 seems to work so far.
For me, it's a bit different, it compiles, installs, and sorts of runs. The console stays clear of errors, but instead of my components in the app, I see a wall of text with this error.

As a side note, the same error is present in ui-material components past version 5.2.10 as described [here](https://github.com/nativescript-community/ui-material-components/issues/259)

**Comment by OzymandiasTheGreat** [comment]
Ok, so for me it was due to outdated dependencies, in the package.json I had @angular packages pinned as `~11.0.0` from the starter template. Switching to `^` fixed the issue.

**Comment by keerl** [comment]
This should no longer be an issue. Plugin has been updated to Angular 12.2.0 and is working again using all the latest dependencies.
